### ISSUE TITLE
How to run?Test Failure

### ISSUE THREAD

**Issue by feitianlong** [NTumbleBit/NTumbleBit#111]
Hi，i'm a newbie.

when i run  according to your wiki, i encounterred the failure following.  How should i solved the errors?
Thx！

1. United Test
...\myApp\NTumbleBit\NTumbleBit.Tests>dotnet test

Starting test execution, please wait...
[xUnit.net 00:04:54.8093444]     NTumbleBit.Tests.TumblerServerTests.CanGenerateAddress [FAIL]
NTumbleBit.Tests.TumblerServerTests.CanGenerateAddress Failure

Failure information:
 Assert.Equal() Failure
Expected: 0'/0'/2'
Actual:   0'/0'/1'
Stack trace:
   at NTumbleBit.Tests.TumblerServerTests.CanGenerateAddress() in ...\NTumbleBit.Tests\TumblerServerTests.cs:line 142

NTumbleBit.Tests  Total test: 17. Has passed: 16. Failure: 1. Skipped: 0. Time: 4.9320m
The test failed to run.

2. Server Test
...\NTumbleBit\NTumbleBit.ClassicTumbler.Server.CLI>dotnet run -testnet

- info: Configuration:  Using cycle shorty2x
- info: Configuration:  Testing RPC connection to http://localhost:18332/
- fail: Configuration:  Error connecting to RPC server The remote server returned an error: (401) Unauthorized.
- fail: Configuration:  Please, fix rpc settings in...

-bitcoin.conf

```
# Run on the test network instead of the real bitcoin network.
testnet=1

# server=1 tells Bitcoin-Qt and bitcoind to accept JSON-RPC commands
server=1

# RPC user and password may be used if you aren't using the newer 'cookie' authentication
rpcuser=bitcoinuser
rpcpassword=bitcoinuser

# Optional: pruning can reduce the disk usage from currently around 120GB (or 8GB testnet) to around 2 GB.
prune=2000

```
-server.config

```
####Common Commands####
#Connection to the input wallet. TumbleBit.CLI will try to autoconfig based on default settings of Bitcoin Core.
#rpc.url=http://localhost:18332/  # assumes Bitcoin Core is on localhost  
#rpc.user=bitcoinuser         # use the credentials from your bitcoin.conf
#rpc.password=bitcoinuser     # use the credentials from your bitcoin.conf
#rpc.cookiefile=yourbitcoinfolder/.cookie


####Tumbler settings####
## The fees in BTC
#tumbler.fee=0.01
## The cycle used among Kotori,Shorty,Shorty2x
#cycle=kotori


####Server Commands####
#port=37123
#listen=0.0.0.0


####Tor configuration (default is enabled, using cookie auth or no auth on Tor control port 9051)####
#tor.enabled=true
#tor.server=127.0.0.1:9051
#tor.password=mypassword
#tor.cookiefile=/path/to/my/cookie/file
#tor.virtualport=80


####Debug Commands####
#Whether or not the tumbler deliver puzzle's solution off chain to the client (default: true)
#cooperative=false



```

**Comment by D3m0nKingx** [comment]
I confirm the same Error occurring in Testing, Also I'm having 2 other errors:


```C#
Failed   NTumbleBit.Tests.TumblerServerTests.CanCompleteCycleWithMachineState
Error Message:
 System.OperationCanceledException : The operation was canceled.
Stack Trace:
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at NTumbleBit.Tests.TumblerServerTests.WaitStatus(PaymentStateMachine machine, PaymentStateMachineStatus state) in /home/demon/coins/NTumbleBit/NTumbleBit.Tests/TumblerServerTests.cs:line 347
   at NTumbleBit.Tests.TumblerServerTests.CanCompleteCycleWithMachineStateCore(Boolean cooperativeClient, Boolean cooperativeTumbler) in /home/demon/coins/NTumbleBit/NTumbleBit.Tests/TumblerServerTests.cs:line 209
   at NTumbleBit.Tests.TumblerServerTests.CanCompleteCycleWithMachineState() in /home/demon/coins/NTumbleBit/NTumbleBit.Tests/TumblerServerTests.cs:line 102
2018-09-06 23:44:58 
```
and
```C#
Failed   NTumbleBit.Tests.TumblerServerTests.EscrowGetRedeemedIfTimeout
Error Message:
 The collection contained 0 matching element(s) instead of 1.
Stack Trace:
   at NTumbleBit.Tests.TumblerServerTests.EscrowGetRedeemedIfTimeoutCore(Boolean fulfill) in /home/demon/coins/NTumbleBit/NTumbleBit.Tests/TumblerServerTests.cs:line 412
   at NTumbleBit.Tests.TumblerServerTests.EscrowGetRedeemedIfTimeout() in /home/demon/coins/NTumbleBit/NTumbleBit.Tests/TumblerServerTests.cs:line 366
2018-09-06 23:48:29 
```

**Comment by D3m0nKingx** [comment]
@feitianlong you need to uncomment the rpc.user/password lines in the server.conf so change:

#rpc.user=bitcoinuser       
#rpc.password=bitcoinuser  

to 

rpc.user=bitcoinuser         
rpc.password=bitcoinuser  

The bang symbol '#' is equivalent to saying = ignore this line when a program reads it.

**Comment by NicolasDorier** [comment]
Run the test again, I think those tests are quite flaky :/ I though having fixed it last time I worked on TB

**Comment by D3m0nKingx** [comment]
I ran the tests 3 times, same 3 keep failing. Is there something else I should do before executing `dotnet test` in that folder ?

**Comment by NicolasDorier** [comment]
I will need to take a look :/ pretty sure it was working last time I ran the project.

**Comment by feitianlong** [comment]
Thx two guys。
Run test again after uncomment #.   The fail still exists！
```
fail: Configuration:  Error connecting to RPC server The remote server returned an error: (404) Not Found.
fail: Configuration:  Please, fix rpc settings in ...
```

**Comment by NicolasDorier** [comment]
@feitianlong you don't have the same error as @D3m0nKingx for the tests. Can you run tests again?

**Comment by feitianlong** [comment]
@NicolasDorier  test again.

United test
```
C:\Users\...\myApp\NTumbleBit\NTumbleBit.Tests>dotnet test
Started generation, please wait...
Completed build.

Test run of C:\Users\...\myApp\NTumbleBit\NTumbleBit.Tests\bin\Debug\netcoreapp2.1\NTumbleBit.Tests.dll (.NETCoreApp, Version=v2.1)
Microsoft (R) Test Execution Command Line Tool version 15.8.0
Copyright (C) Microsoft Corporation. all rights reserved.

Starting test execution, please wait...
[xUnit.net 00:04:58.6385730] NTumbleBit.Tests.TumblerServerTests.CanGenerateAddress [FAIL]
NTumbleBit.Tests.TumblerServerTests.CanGenerateAddress failed
wrong information:
  Assert.Equal() Failure
Expected: 0'/0'/2'
Actual: 0'/0'/1'
Stack trace:
    At NTumbleBit.Tests.TumblerServerTests.CanGenerateAddress() in C:\Users\...\myApp\NTumbleBit\NTumbleBit.Tests\TumblerServerTests.cs:line 142

Total test: 17. Has passed: 16. Failure: 1. Skipped: 0.
The test failed to run.
Test execution time: 5.0039 minutes
```

**Comment by feitianlong** [comment]
@D3m0nKingx  Has the error occurring in Testing been resolved?  I have not solved this problem so far. 
THX！！！！

**Comment by D3m0nKingx** [comment]
@feitianlong not yet afaik

**Comment by feitianlong** [comment]
@D3m0nKingx @NicolasDorier  I ran the project in the Windows10 now,.

Excecuting `dotnet test`

```
[xUnit.net 00:05:16.7323251] NTumbleBit.Tests.TumblerServerTests.CanGenerateAddress [FAIL]
NTumbleBit.Tests.TumblerServerTests.CanGenerateAddress failed
wrong information:
  Assert.Equal() Failure
Expected: 0'/0'/2'
Actual: 0'/0'/1'
Stack trace:
    At NTumbleBit.Tests.TumblerServerTests.CanGenerateAddress() in C:\Users\oneftl\myApp\NTumbleBit\NTumbleBit.Tests\TumblerServerTests.cs:line 142
```
TumblerServerTests.cs:line 142 : `Assert.Equal(new KeyPath("0'/0'/2'"), wrpc.GetKeyPath(k1));`

According to wrong information, i modified the codes form `Assert.Equal(new KeyPath("0'/0'/2'"), wrpc.GetKeyPath(k1)); ` to `Assert.Equal(new KeyPath("0'/0'/1'"), wrpc.GetKeyPath(k1));`

The shell shows:
```
[xUnit.net 00:06:09.0399047] NTumbleBit.Tests.TumblerServerTests.CanGenerateAddress [FAIL]
NTumbleBit.Tests.TumblerServerTests.CanGenerateAddress failed
wrong information:
  Assert.Equal() Failure
Expected: 0'/0'/3'
Actual: 0'/0'/2'
Stack trace:
    At NTumbleBit.Tests.TumblerServerTests.CanGenerateAddress() in C:\Users\oneftl\myApp\NTumbleBit\NTumbleBit.Tests\TumblerServerTests.cs:line 143

Total test: 17. Has passed: 16. Failure: 1. Skipped: 0.
The test failed to run.
```
TumblerServerTests.cs:line 143: `Assert.Equal(new KeyPath("0'/0'/2'"), wrpc.GetKeyPath(k2));`

According to wrong information, i modified the codes again
form `Assert.Equal(new KeyPath("0'/0'/3'"), wrpc.GetKeyPath(k2)); `
to `Assert.Equal(new KeyPath("0'/0'/2'"), wrpc.GetKeyPath(k2));`
The shell shows:
```
Total test: 17. Has passed: 17. Failure: 0. Skipped: 0.
The test runs successfully.
```

Is it possible that the code is wrong? But someone, such as @D3m0nKingx , had succeeded in running the project in the past.

So i want to ask some issues. 
1. What happens to the project after modifying the code? 
2. Whether it effect on functions of Tumbler？
3. Why the test runs successfully after modifying these code?

THX!!!!

**Comment by feitianlong** [comment]
@NicolasDorier @D3m0nKingx 
Although the first problem is solved, the second problem still exists.
```
C:\Users\...\myApp\NTumbleBit\NTumbleBit.ClassicTumbler.Server.CLI>dotnet run -testnet
Use boot settings from C:\Users\...\myApp\NTumbleBit\NTumbleBit.ClassicTumbler.Server.CLI\Properties\launchSettings.json
Info: Configuration: Using APPDATA environment variable for initializing application data
Info: Configuration: Configuration file set to C:\Users\...\AppData\Roaming\NTumbleBitServer\TestNet\server.config
Info: Configuration: Network: TestNet
Info: Configuration: Data directory set to C:\Users\...\AppData\Roaming\NTumbleBitServer\TestNet
Info: Configuration: Configuration file set to C:\Users\...\AppData\Roaming\NTumbleBitServer\TestNet\server.config
Info: Configuration: Using cycle kotori
Info: Configuration: Testing RPC connection to http://localhost:18332/
Fail: Configuration: Error connecting to RPC server The remote server returned an error: (401) Unauthorized.
Fail: Configuration: Please, fix rpc settings in C:\Users\...\AppData\Roaming\NTumbleBitServer\TestNet\server.config
```
The bitcoin.config:
```
# Run on the test network instead of the real bitcoin network.
testnet=1

# server=1 tells Bitcoin-Qt and bitcoind to accept JSON-RPC commands
server=1

# RPC user and password may be used if you aren't using the newer 'cookie' authentication
rpcuser=bitcoinuser
rpcpassword=bitcoinpassword

# Optional: pruning can reduce the disk usage from currently around 120GB (or 8GB testnet) to around 2 GB.
prune=2000
```
And server.config:
```
####Common Commands####
#Connection to the input wallet. TumbleBit.CLI will try to autoconfig based on default settings of Bitcoin Core.
rpc.url=http://localhost:18332

rpc.user=bitcoinuser         # use the credentials from your bitcoin.conf
rpc.password=bitcoinpassword     # use the credentials from your bitcoin.conf
###rpc.cookiefile=yourbitcoinfolder/.cookie###

####Tumbler settings####
## The fees in BTC
tumbler.fee=0.01
## The cycle used among Kotori,Shorty,Shorty2x
cycle=kotori


####Server Commands####
port=37123
listen=0.0.0.0


####Tor configuration (default is enabled, using cookie auth or no auth on Tor control port 9051)####
tor.enabled=true
tor.server=127.0.0.1:9051
tor.password=mypassword
tor.cookiefile=/path/to/my/cookie/file
tor.virtualport=80


####Debug Commands####
#Whether or not the tumbler deliver puzzle's solution off chain to the client (default: true)
cooperative=false

```

1. Why is it still ` Error connecting to RPC server The remote server returned an error: (401) Unauthorized.`?
2. How to fix server.conf ? 
3. By the way ,I find that the comment is **confusing** like this:
- ![image](https://user-images.githubusercontent.com/39018130/46247165-f0630000-c439-11e8-8d0c-04557f6dd03b.png)

- ![image](https://user-images.githubusercontent.com/39018130/46247155-c7db0600-c439-11e8-96e5-260a40cb45ae.png)

And how should i do something to run the project fine?  THX!!!

**Comment by feitianlong** [comment]
@NicolasDorier 
I success to run the server:
![image](https://user-images.githubusercontent.com/39018130/46255524-877a9700-c4d0-11e8-98c3-5e254305e1d2.png)
But i can't run the client,the error is this:
![image](https://user-images.githubusercontent.com/39018130/46255541-babd2600-c4d0-11e8-90ae-c9bb78542e44.png)
And the near code in _TextFileConfiguration.cs_ is 
```
else if(typeof(T) == typeof(TumblerUrlBuilder))
            {
               
                try
                {
                    System.Console.WriteLine("**************  enter the try " + "***********"); //add by zyx
                    return (T)(object)new TumblerUrlBuilder(str);
                }
                catch { throw new ConfigException("Invalid tumbler uri"); }
            }
```
I can local the wrong is `return (T)(object)new TumblerUrlBuilder(str);` , but i don't know how to fix it.

**Comment by NicolasDorier** [comment]
@feitianlong what is your tumbleruri ? Should start by `onion:`

**Comment by feitianlong** [comment]
@NicolasDorier ok !   Do i need to  strat by the onion router?  So  should i install Tor broswer? And config Tor?

`tumbler.server=http://localhost:37123/`

client.config :
```
####Common Commands####
#Connection to the input wallet. TumbleBit.CLI will try to autoconfig based on default settings of Bitcoin Core.
rpc.url=http://localhost:18332/
rpc.user=bitcoinuser
rpc.password=bitcoinpassword
#rpc.cookiefile=yourbitcoinfolder/.cookie

#Tumbler server to connect to
tumbler.server=http://localhost:37123/
# Wallet
outputwallet.extpubkey=2MvnY1EMvGH29KJT45hbyeuVKtJgpSixo6v
outputwallet.keypath=

####Connection Commands####
#Making Alice or Bob pass through TOR (Recommended, the circuit will change for each cycle/persona)
#The default settings you run `tor -controlport 9051 -cookieauthentication 1`
alice.proxy.type=tor
alice.proxy.server=127.0.0.1:9051
alice.proxy.password=padeiwmnfw
alice.proxy.cookiefile=/var/run/tor/control.authcookie
#or
bob.proxy.type=tor
bob.proxy.server=127.0.0.1:9051
bob.proxy.password=padeiwmnfw
bob.proxy.cookiefile=/var/run/tor/control.authcookie


####Debug Commands####
#Whether or not signature for the escape transaction is transmitted to the Tumbler (default: true)
cooperative=false
#Whether or not IP sharing between Bob and Alice is authorized (default: true for testnets, false for mainnet)
allowinsecure=true

# Bitcoin Core
rpc.url=http://localhost:18332/
rpc.user=bitcoinuser
rpc.password=bitcoinpassword
```
corresponding server.conf  following:
```
rpc.url=http://localhost:18332/
rpc.user=bitcoinuser
rpc.password=bitcoinpassword

tumbler.fee=0.01
cycle=Kotori
port=37123
listen=0.0.0.0

tor.enabled=true
tor.server=127.0.0.1:9051
tor.password=mypassword
tor.cookiefile=/path/to/my/cookie/file
tor.virtualport=80

cooperative=false
```

**Comment by NicolasDorier** [comment]
`tumbler.server=http://localhost:37123/` this is not what you should set, the server give you onion links normally.

**Comment by D3m0nKingx** [comment]
@NicolasDorier I see bitcoin core is on 0.17.0 any plans to update?

**Comment by NicolasDorier** [comment]
I will soon, that and another update on something I noticed here.

**Comment by NicolasDorier** [comment]
I will update things end of this week as well as fix the vulnerability I found out.

**Comment by feitianlong** [comment]
@D3m0nKingx @NicolasDorier 
i did run the project, but something wrong!
These two questions confused me!

Bitcoin Core Version:0.16.0

The shell shows following
![image](https://user-images.githubusercontent.com/39018130/46952733-4d0f1d80-d0be-11e8-8120-ac6e712a4445.png)

**1.** Why the  `Should stay connected` shows ` False` instand of `True`?(I dont know the standred result,i guess it is ture.)

 I located the codes (**PaymentStateMachine.cs:line:527**) in:
```
 if (
	// You get the solution of the puzzle
	Status == PaymentStateMachineStatus.PuzzleSolutionObtained &&
	// But have not yet cashed out
	!IsConfirmed(cycle, TransactionType.TumblerCashout))
       {
	return true;
	}
 if (
	// You do not have the solution
	Status == PaymentStateMachineStatus.UncooperativeTumbler &&
	// But have not yet redeemed or cashed out
	!(IsConfirmed(cycle, TransactionType.ClientRedeem) || IsConfirmed(cycle, TransactionType.ClientOfferRedeem) || IsConfirmed(cycle, TransactionType.TumblerCashout)))
	{
		return true;
	}

```
and the **_Status == PaymentStateMachineStatus.PuzzleSolutionObtained_** is **_false_**,so is **_Status == PaymentStateMachineStatus.UncooperativeTumbler_**,which is why I got _False_ in  `Should stay connected: False` ,how to reslove it?

**2.** Why Records is just two phases? According to  [your wiki result](https://github.com/NTumbleBit/NTumbleBit/wiki/How-to-Run#5-command-line-interface),there shouldn't  be only two phases. 
The two phases indicates that the client dont seem to connect to tumbler so that it dont realize the payment of spending the coins in her escrow to an output.In other words, there's not  seem to mix coins.

**Comment by NicolasDorier** [comment]
`Should stay connected` is `true` when you risk loosing money by disconnecting at this precise moment.

`ClientChannelBroadcasted` just mean that you did your channel, so no risk of loosing money here.

**Comment by feitianlong** [comment]
So what about the second question? It seems that there are no Tumbler `Escow and Tumbler Redeem transactions` generated, only `ClientEscorw transaction and ClientRedeem transaction`.
And my output wallet didn't get Alice's money, and the money was returned to Alice's wallet.

**Comment by NicolasDorier** [comment]
Probably because your tumbler does not have enough liquidity to tumble. Does it?

**Comment by feitianlong** [comment]
Pardon me! What does enough liquidity mean?   enough tumble node or money(using shorty cycle.And there are 1B), or other?

**Comment by NicolasDorier** [comment]
Your tumbler need as money in the wallet so it can tumble.

**Comment by feitianlong** [comment]
All right!
I only have one test coin now. How much does it need to satisfy?  
Can you give me some test coin? 
address: 2N5pRBYdBtmL4MJmbmSq2Dcsrhm79VdFf3u

**Comment by NicolasDorier** [comment]
I don't have any

**Comment by feitianlong** [comment]
My understanding of tumbler is middleman (i.e server?), running tumble server, how do I know how much money tumbler has and how to charge tumbler?

**Comment by NicolasDorier** [comment]
I don't remember the denomination of `Kotori`, but if 1 round is 0.1 BTC, then the tumbler need 0.1 BTC per participants in its wallet.

**Comment by feitianlong** [comment]
All right!
The client(Alice) is connected to the bitcoin core wallet(by rpc), and the server(tumbler) is also connected to the bitcoin core wallet (by rpc)? Then the bitcoin core wallet acts both as Alice's wallet and as a tumbler wallet, right?
`FriendlyName = "Shorty",	Consensus = consensus,		Denomination = Money.Coins(0.01m)`
If I use the shorty cycle(the denomination of shorty is 0.01m), then my wallet balance (1BTC) is completely sufficient for tumble. Is my understanding correct? If so, then my problem should not be that tumbler is not sufficiently liquidility to generate escow transactions.
So I never understood where something went wrong and I never finished tumble because Bob didn't receive the money.
Thank you for your attention to this matter!!

**Comment by NicolasDorier** [comment]
You need Alice, Tumbler and Bob, each with their own wallet, each with enough money to tumble.

**Comment by NicolasDorier** [comment]
Make a tumbler: Create 3 Alices which connect to it. Put to each of those alice and the tumbler some money to it, and wait. It will happen.

**Comment by NicolasDorier** [comment]
I don't know why the tumble cycle does not go through, but you can try to get some info by doing `status <cycleId>` and see what it tells you on the tumbler

**Comment by feitianlong** [comment]
Create 3 Alice means 3 pcs to run the client? 
Because my pc can only start a Client (I don't know how a PC runs multiple clients).

**Comment by NicolasDorier** [comment]
can be same PC. But I can't tell you why it is not tumbling only with the data you give me here.

**Comment by feitianlong** [comment]
1. Is the same wallet used by Client and Tumbler? If not, how do you give Tumbler money?
2. How to create 3 Alice in same PC? Because every time I `donet run -testnet` Client.Cli again, there will be info following
```
fail: Broadcasters:   Exception on TrustedBroadcaster
fail: Broadcasters:   DBreeze.Exceptions.DBreezeException: Creation of the database folder failed! ---> DBreeze.Exceptions.DBreezeException: Database is not operable, please find out the problem and restart the engine! FSR INIT FAILED: C:\Users\oneftl\AppData\Roaming\NTumbleBit\TestNet\db2\TrustedBroadcasts\_DBreezeSchema ---> System.IO.IOException: The process cannot access the file 'C:\Users\oneftl\AppData\Roaming\NTumbleBit\TestNet\db2\TrustedBroadcasts\_DBreezeSchema' because it is being used by another process.
```

**Comment by NicolasDorier** [comment]
look the command line with `--help` and choose another folder.

**Comment by D3m0nKingx** [comment]
@NicolasDorier just an fyi that bitcoin's ppa repository now officially installs bitcoin v0.17.0 for linux:
```
demon@UbuntuHP:~$ apt list -a bitcoind
Listing... Done
bitcoind/xenial,now 0.17.0-xenial1 amd64 [installed]
```

**Comment by feitianlong** [comment]
@NicolasDorier 
1. The following error occurs when I run the client.Does this affect tumbler?
```
fail: Client:         Unhandled StateMachine Error
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at TCPServer.Extensions.ReadByteAsync(Stream stream, CancellationToken cts)
   at TCPServer.ServerImplemetation.TCPStream.ReadVarIntAsync()
   at TCPServer.Client.TCPHttpMessageHandler.GetResponseAsync(TCPStream tcpStream)
   at TCPServer.Client.TCPHttpMessageHandler.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at TCPServer.Client.TCPHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at NTumbleBit.ClassicTumbler.Client.TumblerClient.SendAsync[T](HttpMethod method, IBitcoinSerializable body, String relativePath, Object[] parameters) in C:\Users\oneftl\myApp\NTumbleBit\NTumbleBit\ClassicTumbler\Client\TumblerClient.cs:line 151
   at NTumbleBit.ClassicTumbler.Client.TumblerClient.AskUnsignedVoucher() in C:\Users\oneftl\myApp\NTumbleBit\NTumbleBit\ClassicTumbler\Client\TumblerClient.cs:line 61
   at NTumbleBit.ClassicTumbler.Client.PaymentStateMachine.Update() in C:\Users\oneftl\myApp\NTumbleBit\NTumbleBit\ClassicTumbler\Client\PaymentStateMachine.cs:line 225
   at NTumbleBit.ClassicTumbler.Client.StateMachinesExecutor.<>c__DisplayClass12_0.<StartCore>b__0() in C:\Users\oneftl\myApp\NTumbleBit\NTumbleBit\ClassicTumbler\Client\StateMachinesExecutor.cs:line 93
```
2. And I did a status cycleID (same ID) on the command line of the server and the command line of the client, and got different infos. Why is it?
Client>>status 1437893
![image](https://user-images.githubusercontent.com/39018130/47138006-c428f980-d2ea-11e8-81a0-0178b7d58dd6.png)
Server>>status 1437893
![image](https://user-images.githubusercontent.com/39018130/47138043-e3c02200-d2ea-11e8-97a2-58e19bf18dae.png)

3. Since server and Bob also need to establish a payment channel, can it be implemented only by configuring Bob's expubkey in client.conf? Because I don't think there is Tumbler's Escrow Transaction, it may be because Server does not establish a connection with Bob.

**Comment by NicolasDorier** [comment]
It is normal that server and the server does not show the same info.  No concern for the exception.

Though it should show in the logs of the server what is happening when a Client escrow has been done for example. Copy paste all your server logs.

**Comment by feitianlong** [comment]
@NicolasDorier Thank you very much for your patience.
**Server:**
```
PS C:\Users\oneftl\myApp\NTumbleBit\NTumbleBit.ClassicTumbler.Server.CLI> dotnet run -testnet
从 C:\Users\oneftl\myApp\NTumbleBit\NTumbleBit.ClassicTumbler.Server.CLI\Properties\launchSettings.json 使用启动设置...
info: Configuration:  Using APPDATA environment variable for initializing application data
info: Configuration:  Configuration file set to C:\Users\oneftl\AppData\Roaming\NTumbleBitServer\TestNet\server.config
info: Configuration:  Network: TestNet
info: Configuration:  Data directory set to C:\Users\oneftl\AppData\Roaming\NTumbleBitServer\TestNet
info: Configuration:  Configuration file set to C:\Users\oneftl\AppData\Roaming\NTumbleBitServer\TestNet\server.config
info: Configuration:  Using cycle Shorty
info: Configuration:  Testing RPC connection to http://localhost:18332/
info: Configuration:  RPC connection successfull
info: Configuration:  Bitcoin Core version detected: 160000
info: Configuration:  Successfully authenticated to Tor
info: Configuration:  Tor configured on http://knf4dfwqeem7eglo.onion/
info: Configuration:  RSA private key found (C:\Users\oneftl\AppData\Roaming\NTumbleBitServer\TestNet\Tumbler.pem)
info: Configuration:  Poupard Stern Proof found (C:\Users\oneftl\AppData\Roaming\NTumbleBitServer\TestNet\ProofPoupard-Tumbler.pem)
info: Configuration:  Permutation Test Proof found (C:\Users\oneftl\AppData\Roaming\NTumbleBitServer\TestNet\ProofPermutation-Tumbler.pem)
info: Configuration:  RSA private key found (C:\Users\oneftl\AppData\Roaming\NTumbleBitServer\TestNet\Voucher.pem)
info: Configuration:  Poupard Stern Proof found (C:\Users\oneftl\AppData\Roaming\NTumbleBitServer\TestNet\ProofPoupard-Voucher.pem)
info: Configuration:  Permutation Test Proof found (C:\Users\oneftl\AppData\Roaming\NTumbleBitServer\TestNet\ProofPermutation-Voucher.pem)
info: Configuration:  --------------------------------
info: Configuration:  Shareable URIs of the running tumbler are:
info: Configuration:  ctb://knf4dfwqeem7eglo.onion?h=90c8c1e5186dedd822d0a1a18a02b984478eb4aa
info: Configuration:  --------------------------------
info: Broadcasters:   BroadcasterJob started
info: Tumbler:        Tor Register job started
NTumbleBit.TumblerServer 1.0.0.0 -- TumbleBit Implementation in .NET Core
Type "help" or "help <command>" for more information.
>>> info: Wallet:         Updated 113 cached transactions in 0 seconds
info: Broadcasters:   Broadcasted 0 transaction(s), monitoring 0 entries in 0 seconds
info: Broadcasters:   Trusted Broadcaster is monitoring 0 entries in 0 seconds
Hosting environment: Development
Content root path: C:\Users\oneftl\myApp\NTumbleBit\NTumbleBit.ClassicTumbler.Server.CLI
Now listening on: http://127.0.0.1:37123/
```
**Client:**
```
PS C:\Users\oneftl\myApp\NTumbleBit\NTumbleBit.ClassicTumbler.Client.CLI> dotnet run -testnet
从 C:\Users\oneftl\myApp\NTumbleBit\NTumbleBit.ClassicTumbler.Client.CLI\Properties\launchSettings.json 使用启动设置...
info: Configuration:  Using APPDATA environment variable for initializing application data
info: Configuration:  Configuration file set to C:\Users\oneftl\AppData\Roaming\NTumbleBit\TestNet\client.config
info: Configuration:  Network: TestNet
info: Configuration:  Data directory set to C:\Users\oneftl\AppData\Roaming\NTumbleBit\TestNet
info: Configuration:  Configuration file set to C:\Users\oneftl\AppData\Roaming\NTumbleBit\TestNet\client.config
info: Configuration:  Testing RPC connection to http://localhost:18332/
info: Configuration:  RPC connection successfull
info: Configuration:  Bitcoin Core version detected: 160000
info: Configuration:  Using tumbler ctb://knf4dfwqeem7eglo.onion?h=90c8c1e5186dedd822d0a1a18a02b984478eb4aa
info: Broadcasters:   BroadcasterJob started
NTumbleBit.CLI 1.0.0.0 -- TumbleBit Implementation in .NET Core
Type "help" or "help <command>" for more information.
>>> info: Client:         State machines started
info: Client:         New Block: 1439493
info: Client:         New Cycle: 1439493
info: Wallet:         Updated 113 cached transactions in 0 seconds
info: Broadcasters:   Broadcasted 0 transaction(s), monitoring 113 entries in 0 seconds
info: Broadcasters:   Broadcasted 3586a69c74807fc69cdbd27d862f5a27a43e30c6f20f9c0ff9b69100f6eb1f7c
info: Broadcasters:   Broadcasted 4fb8a95ea60d8456e1175d7192c356f9436c6b5a68e20655c6c12979ac507038
info: Broadcasters:   Broadcasted ClientRedeem of cycle 1439335 planned on block 1439350
info: Broadcasters:   Broadcasted ClientRedeem of cycle 1439341 planned on block 1439356
info: Broadcasters:   Trusted Broadcaster is monitoring 45 entries in 0 seconds
info: Wallet:         Updated 115 cached transactions in 0 seconds
info: Broadcasters:   Broadcasted 3586a69c74807fc69cdbd27d862f5a27a43e30c6f20f9c0ff9b69100f6eb1f7c
info: Broadcasters:   Broadcasted 4fb8a95ea60d8456e1175d7192c356f9436c6b5a68e20655c6c12979ac507038
info: Broadcasters:   Broadcasted 2 transaction(s), monitoring 115 entries in 0 seconds
info: Broadcasters:   Trusted Broadcaster is monitoring 37 entries in 0 seconds
info: Client:         Cycle 1439493 (New)
info: Client:         {[.o.].[..].[..].[[..]..][..].} in phase Registration (2 more blocks)
info: Client:         Status changed New => Registered
info: Client:         New Block: 1439494
info: Client:

info: Client:         Cycle 1439493 (Registered)
info: Client:         {[.o.].[..].[..].[[..]..][..].} in phase Registration (2 more blocks)
info: Wallet:         Updated 115 cached transactions in 0 seconds
info: Broadcasters:   Broadcasted 0 transaction(s), monitoring 115 entries in 0 seconds
info: Broadcasters:   Trusted Broadcaster is monitoring 37 entries in 0 seconds
info: Client:         New Block: 1439495
info: Client:         New Cycle: 1439495
info: Client:
```

**Comment by NicolasDorier** [comment]
Wait long enough until the client go into some other cycle, I need to see why the tumbler does not create channel, normally it gives message about it.

**Comment by feitianlong** [comment]
Is it enough?
Although the log file shows how TumblerChannelEstablishment is, I still don't understand why I can't tumble
[log.txt](https://github.com/NTumbleBit/NTumbleBit/files/2494859/log.txt)

**Comment by NicolasDorier** [comment]
and logs of tumbler? this is logs of client.

**Comment by feitianlong** [comment]
@NicolasDorier 
[logs.txt](https://github.com/NTumbleBit/NTumbleBit/files/2495050/logs.txt)

**Comment by NicolasDorier** [comment]
Ok so from the logs, nothing particular seems to go wrong. So I think it might have to do with the fact that Testnet is quite unreliable with lot's of reorg, or like fast block coming on.

I would advise you to try with RegTest so you can mine by yourself. Else wait a bit.

The state is of your client was  `TumblerVoucherSigning` for 1439503, and judging the logs of tumbler, the tumbler signed the voucher.

After this, your client should have moved to the `TumblerVoucherObtained` status. But it did not. I don't think there is a bug, or tests would have caught it. Though this issue might happen if blocks are generated too fast, this happen a lot on testnet.

No cycle worked since beginning?

**Comment by feitianlong** [comment]
Yes.    Never

**Comment by NicolasDorier** [comment]
I will try myself, though I am quite confident this is caused by bad testnet generating blocks too fast. Please send me more logs of both tumbler and server if you have.

**Comment by feitianlong** [comment]
@NicolasDorier 
Log generated when syncing blocks.
Testnet 
[ServerLogs_testnet.txt](https://github.com/NTumbleBit/NTumbleBit/files/2510940/ServerLogs_testnet.txt)
[ClientLogs_testnet.txt](https://github.com/NTumbleBit/NTumbleBit/files/2510941/ClientLogs_testnet.txt)
RegTest
[ServerLogs_regTest.txt](https://github.com/NTumbleBit/NTumbleBit/files/2510943/ServerLogs_regTest.txt)
[ClientLogs_regTest.txt](https://github.com/NTumbleBit/NTumbleBit/files/2510944/ClientLogs_regTest.txt)
