### ISSUE TITLE
 System.UnauthorizedAccessException: Access to the path '/var/lib/tor/control_auth_cookie' is denied.

### ISSUE THREAD

**Issue by FyreDemonyte** [NTumbleBit/NTumbleBit#113]
```C#
fail: Tumbler:        Exception thrown while running the server
fail: Tumbler:        System.UnauthorizedAccessException: Access to the path '/var/lib/tor/control_auth_cookie' is denied. ---> System.IO.IOException: Permission denied
         --- End of inner exception stack trace ---
         at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
         at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
         at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
         at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
         at System.IO.File.ReadAllBytes(String path)
         at NTumbleBit.Tor.TorClient.AuthenticateAsync(CancellationToken ctsToken) in /home/demon/coins/NTumbleBit/NTumbleBit/Tor/TorClient.cs:line 108
         at NTumbleBit.ClassicTumbler.Client.ConnectionSettings.TorConnectionSettings.TryConnectAsync() in /home/demon/coins/NTumbleBit/NTumbleBit/ClassicTumbler/Client/ConnectionSettings/TorConnectionSettings.cs:line 113
         at NTumbleBit.ClassicTumbler.Client.ConnectionSettings.TorConnectionSettings.SetupAsync(ClientInteraction interaction, String torPath) in /home/demon/coins/NTumbleBit/NTumbleBit/ClassicTumbler/Client/ConnectionSettings/TorConnectionSettings.cs:line 147
         at NTumbleBit.ClassicTumbler.Server.TumblerRuntime.ConfigureAsyncCore(TumblerConfiguration conf, ClientInteraction interaction) in /home/demon/coins/NTumbleBit/NTumbleBit/ClassicTumbler/Server/TumblerRuntime.cs:line 67
         at NTumbleBit.ClassicTumbler.Server.TumblerRuntime.ConfigureAsync(TumblerConfiguration conf, ClientInteraction interaction) in /home/demon/coins/NTumbleBit/NTumbleBit/ClassicTumbler/Server/TumblerRuntime.cs:line 37
         at NTumbleBit.ClassicTumbler.Server.TumblerRuntime.FromConfigurationAsync(TumblerConfiguration conf, ClientInteraction interaction) in /home/demon/coins/NTumbleBit/NTumbleBit/ClassicTumbler/Server/TumblerRuntime.cs:line 30
         at NTumbleBit.ClassicTumbler.Server.TumblerRuntime.FromConfiguration(TumblerConfiguration conf, ClientInteraction interaction) in /home/demon/coins/NTumbleBit/NTumbleBit/ClassicTumbler/Server/TumblerRuntime.cs:line 23
         at NTumbleBit.ClassicTumbler.Server.CLI.Program.Run(String[] args) in /home/demon/coins/NTumbleBit/NTumbleBit.ClassicTumbler.Server.CLI/Program.cs:line 43
```
This is actually an old problem I've come across that I've found at this point is only one work-around, and is also the reason I think most people aren't getting this error is because they're running the server as root user, and most users probably run this on a server which is by default logged in as root#.

So when you run NTumbleBit as a non-sudo user this error will occur because the TOR cookie file is created under root privileges only:

```bash
-rw------- 1 root root 32 Sep  6 20:28 control_auth_cookie
```

 Thus for NTumbleBit to access it you have to start it as superuser with `sudo dotnet run -testnet`

From a security perspective this opens a vulnerability for a hacker to potentially break through the server and have access to the system. 

@NicolasDorier there needs to be another way to make this safely work without needing to run the Tumbler in sudo mode.

**Comment by D3m0nKingx** [comment]
That being if someone wants to use the tor cookie rather than setting a tor password.

**Comment by NicolasDorier** [comment]
the best is to remove the root privileges of the control_auth_cookie.

**Comment by D3m0nKingx** [comment]
Because of the way linux's security/filesystem works and because TOR recreates that directory/cookie on every startup:

If I change the owner/permission of directory /var/lib/tor and the cookie to my $USER. 

Tor will fail on next restart cause it runs as a different user and will not be able to modify that directory/contents:

```
Sep 07 07:55:08 UbuntuHP tor[14563]: Sep 07 07:55:08.324 [warn] /var/lib/tor is not owned by this user (root, 0) but by demon (1000). Perhaps you are running Tor as the wrong user?

```
Tor must be run as the same User as the permissions of the directory it's accessing. Thus this will not work, as I need to run Tor as root due to some specific settings I have in Tor's /etc/tor/torrc config file that only work when it's running as root. 

So changing the owner/permission of the directory / control cookie, would only work temporarily in this situation.
