### ISSUE TITLE
Some tests are randomly failing

### ISSUE THREAD

**Issue by nopara73** [NTumbleBit/NTumbleBit#13]
I tried to induce as much failed tests as possible. Here are the ones those are randomly failing sometimes.  
  
Environment: Windows 7 virtualbox guest.  
  
They are mostly interrelated and the problem is with the test setup. This is not a full list of failed tests.

1. 
```
Test Name:	NTumbleBit.Tests.TumblerServerTests.EscrowGetReddemedIfTimeout
Test FullName:	NTumbleBit.Tests.TumblerServerTests.EscrowGetReddemedIfTimeout
Test Source:	C:\Users\nopara\Desktop\NTumbleBit\NTumbleBit.Tests\TumblerServerTests.cs : line 145
Test Outcome:	Failed
Test Duration:	0:00:21,258

Result StackTrace:	
at System.IO.Win32FileSystem.RemoveDirectoryHelper(String fullPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound)
   at System.IO.Win32FileSystem.RemoveDirectory(String fullPath, Boolean recursive)
   at System.IO.Directory.Delete(String path, Boolean recursive)
   at NTumbleBit.Tests.CoreNode.CleanFolder() in C:\Users\nopara\Desktop\NTumbleBit\NTumbleBit.Tests\NodeBuilder.cs:line 242
   at NTumbleBit.Tests.CoreNode.Kill(Boolean cleanFolder) in C:\Users\nopara\Desktop\NTumbleBit\NTumbleBit.Tests\NodeBuilder.cs:line 460
   at NTumbleBit.Tests.NodeBuilder.Dispose() in C:\Users\nopara\Desktop\NTumbleBit\NTumbleBit.Tests\NodeBuilder.cs:line 171
   at NTumbleBit.Tests.TumblerServerTester.Dispose() in C:\Users\nopara\Desktop\NTumbleBit\NTumbleBit.Tests\TumblerServerTester.cs:line 307
   at NTumbleBit.Tests.TumblerServerTests.EscrowGetReddemedIfTimeout() in C:\Users\nopara\Desktop\NTumbleBit\NTumbleBit.Tests\TumblerServerTests.cs:line 202
Result Message:	Access to the path 'wallet.dat' is denied.
```
  
2. 
```
Test Name:	NTumbleBit.Tests.TumblerServerTests.TestCRUDDBReeze
Test FullName:	NTumbleBit.Tests.TumblerServerTests.TestCRUDDBReeze
Test Source:	C:\Users\nopara\Desktop\NTumbleBit\NTumbleBit.Tests\TumblerServerTests.cs : line 40
Test Outcome:	Failed
Test Duration:	0:00:06,719

Result StackTrace:	
at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.KestrelEngine.CreateServer(ServerAddress address)
   at Microsoft.AspNetCore.Server.Kestrel.KestrelServer.Start[TContext](IHttpApplication`1 application)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.Start()
   at NTumbleBit.Tests.TumblerServerTester..ctor(String directory) in C:\Users\nopara\Desktop\NTumbleBit\NTumbleBit.Tests\TumblerServerTester.cs:line 186
   at NTumbleBit.Tests.TumblerServerTester.Create(String caller) in C:\Users\nopara\Desktop\NTumbleBit\NTumbleBit.Tests\TumblerServerTester.cs:line 130
   at NTumbleBit.Tests.TumblerServerTests.TestCRUDDBReeze() in C:\Users\nopara\Desktop\NTumbleBit\NTumbleBit.Tests\TumblerServerTests.cs:line 41
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.Check(Int32 statusCode)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvTcpHandle.GetSockIPEndPoint()
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.TcpListener.CreateListenSocket()
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Listener.<>c.<StartAsync>b__6_0(Object state)
Result Message:	
One or more errors occurred. (Error -4091 EADDRINUSE address already in use)
Error -4091 EADDRINUSE address already in use
```

3. 
```
Test Name:	NTumbleBit.Tests.TumblerServerTests.TestCRUDDBReeze
Test FullName:	NTumbleBit.Tests.TumblerServerTests.TestCRUDDBReeze
Test Source:	C:\Users\nopara\Desktop\NTumbleBit\NTumbleBit.Tests\TumblerServerTests.cs : line 40
Test Outcome:	Failed
Test Duration:	0:00:00,028

Result StackTrace:	
at System.IO.Win32FileSystem.RemoveDirectoryHelper(String fullPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound)
   at System.IO.Win32FileSystem.RemoveDirectory(String fullPath, Boolean recursive)
   at System.IO.Directory.Delete(String path, Boolean recursive)
   at NTumbleBit.Tests.TumblerServerTester.TryDelete(String directory, Boolean throws) in C:\Users\nopara\Desktop\NTumbleBit\NTumbleBit.Tests\TumblerServerTester.cs:line 230
   at NTumbleBit.Tests.TumblerServerTester..ctor(String directory) in C:\Users\nopara\Desktop\NTumbleBit\NTumbleBit.Tests\TumblerServerTester.cs:line 150
   at NTumbleBit.Tests.TumblerServerTester.Create(String caller) in C:\Users\nopara\Desktop\NTumbleBit\NTumbleBit.Tests\TumblerServerTester.cs:line 130
   at NTumbleBit.Tests.TumblerServerTests.TestCRUDDBReeze() in C:\Users\nopara\Desktop\NTumbleBit\NTumbleBit.Tests\TumblerServerTests.cs:line 41
Result Message:	The directory is not empty
```

4.
```
Test Name:	NTumbleBit.Tests.TumblerServerTests.CanGetParameters
Test FullName:	NTumbleBit.Tests.TumblerServerTests.CanGetParameters
Test Source:	C:\Users\nopara\Desktop\NTumbleBit\NTumbleBit.Tests\TumblerServerTests.cs : line 23
Test Outcome:	Failed
Test Duration:	0:00:07,667

Result StackTrace:	
at System.IO.Win32FileSystem.RemoveDirectoryHelper(String fullPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound)
   at System.IO.Win32FileSystem.RemoveDirectory(String fullPath, Boolean recursive)
   at System.IO.Directory.Delete(String path, Boolean recursive)
   at NTumbleBit.Tests.CoreNode.CleanFolder() in C:\Users\nopara\Desktop\NTumbleBit\NTumbleBit.Tests\NodeBuilder.cs:line 242
   at NTumbleBit.Tests.CoreNode.Kill(Boolean cleanFolder) in C:\Users\nopara\Desktop\NTumbleBit\NTumbleBit.Tests\NodeBuilder.cs:line 460
   at NTumbleBit.Tests.NodeBuilder.Dispose() in C:\Users\nopara\Desktop\NTumbleBit\NTumbleBit.Tests\NodeBuilder.cs:line 171
   at NTumbleBit.Tests.TumblerServerTester.Dispose() in C:\Users\nopara\Desktop\NTumbleBit\NTumbleBit.Tests\TumblerServerTester.cs:line 307
   at NTumbleBit.Tests.TumblerServerTests.CanGetParameters() in C:\Users\nopara\Desktop\NTumbleBit\NTumbleBit.Tests\TumblerServerTests.cs:line 33
Result Message:	The directory is not empty
```

5.
```
Test Name:	NTumbleBit.Tests.TumblerServerTests.CanGetParameters
Test FullName:	NTumbleBit.Tests.TumblerServerTests.CanGetParameters
Test Source:	C:\Users\nopara\Desktop\NTumbleBit\NTumbleBit.Tests\TumblerServerTests.cs : line 23
Test Outcome:	Failed
Test Duration:	0:00:14,096

Result StackTrace:	
at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebRequest.<>c.<GetResponseAsync>b__37_2(IAsyncResult iar)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NBitcoin.RPC.RPCClient.<SendCommandAsync>d__21.MoveNext() in E:\Sources\NBitcoin\NBitcoin\RPC\RPCClient.cs:line 325
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at NBitcoin.RPC.RPCClient.SendCommand(RPCRequest request, Boolean throwIfRPCError) in E:\Sources\NBitcoin\NBitcoin\RPC\RPCClient.cs:line 288
   at NBitcoin.RPC.RPCClient.GetBestBlockHash() in E:\Sources\NBitcoin\NBitcoin\RPC\RPCClient.cs:line 498
   at NTumbleBit.Tests.CoreNode.Sync(CoreNode node, Boolean keepConnection) in C:\Users\nopara\Desktop\NTumbleBit\NTumbleBit.Tests\NodeBuilder.cs:line 252
   at NTumbleBit.Tests.TumblerServerTester.SyncNodes() in C:\Users\nopara\Desktop\NTumbleBit\NTumbleBit.Tests\TumblerServerTester.cs:line 210
   at NTumbleBit.Tests.TumblerServerTester..ctor(String directory) in C:\Users\nopara\Desktop\NTumbleBit\NTumbleBit.Tests\TumblerServerTester.cs:line 162
   at NTumbleBit.Tests.TumblerServerTester.Create(String caller) in C:\Users\nopara\Desktop\NTumbleBit\NTumbleBit.Tests\TumblerServerTester.cs:line 130
   at NTumbleBit.Tests.TumblerServerTests.CanGetParameters() in C:\Users\nopara\Desktop\NTumbleBit\NTumbleBit.Tests\TumblerServerTests.cs:line 24
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<FinishSendAsync>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.HttpWebRequest.<SendRequest>d__63.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.WinHttpHandler.<StartRequest>d__105.MoveNext()
Result Message:	
An error occurred while sending the request. A connection with the server could not be established
An error occurred while sending the request.
A connection with the server could not be established
```

6.
```
Test Name:	NTumbleBit.Tests.TumblerServerTests.CanCompleteCycleWithMachineState
Test FullName:	NTumbleBit.Tests.TumblerServerTests.CanCompleteCycleWithMachineState
Test Source:	C:\Users\nopara\Desktop\NTumbleBit\NTumbleBit.Tests\TumblerServerTests.cs : line 62
Test Outcome:	Failed
Test Duration:	0:00:07,652

Result StackTrace:	
at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.KestrelEngine.CreateServer(ServerAddress address)
   at Microsoft.AspNetCore.Server.Kestrel.KestrelServer.Start[TContext](IHttpApplication`1 application)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.Start()
   at NTumbleBit.Tests.TumblerServerTester..ctor(String directory) in C:\Users\nopara\Desktop\NTumbleBit\NTumbleBit.Tests\TumblerServerTester.cs:line 186
   at NTumbleBit.Tests.TumblerServerTester.Create(String caller) in C:\Users\nopara\Desktop\NTumbleBit\NTumbleBit.Tests\TumblerServerTester.cs:line 130
   at NTumbleBit.Tests.TumblerServerTests.CanCompleteCycleWithMachineState() in C:\Users\nopara\Desktop\NTumbleBit\NTumbleBit.Tests\TumblerServerTests.cs:line 63
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.Check(Int32 statusCode)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvTcpHandle.GetSockIPEndPoint()
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.TcpListener.CreateListenSocket()
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Listener.<>c.<StartAsync>b__6_0(Object state)
Result Message:	
One or more errors occurred. (Error -4091 EADDRINUSE address already in use)
Error -4091 EADDRINUSE address already in use
```

7.
```
Test Name:	NTumbleBit.Tests.TumblerServerTests.CanCompleteCycleWithMachineState
Test FullName:	NTumbleBit.Tests.TumblerServerTests.CanCompleteCycleWithMachineState
Test Source:	C:\Users\nopara\Desktop\NTumbleBit\NTumbleBit.Tests\TumblerServerTests.cs : line 62
Test Outcome:	Failed
Test Duration:	0:00:07,181

Result StackTrace:	
at DBreeze.DBreezeEngine.InitDb()
   at NTumbleBit.Client.Tumbler.Services.DBreezeRepository.GetEngine(String partitionKey) in C:\Users\nopara\Desktop\NTumbleBit\NTumbleBit.TumblerServer\Services\DBreezeRepository.cs:line 59
   at NTumbleBit.Client.Tumbler.Services.DBreezeRepository.UpdateOrInsert[T](String partitionKey, String rowKey, T data, Func`3 update) in C:\Users\nopara\Desktop\NTumbleBit\NTumbleBit.TumblerServer\Services\DBreezeRepository.cs:line 35
   at NTumbleBit.Client.Tumbler.ClientDestinationWallet..ctor(String walletName, BitcoinExtPubKey extPubKey, KeyPath derivationPath, IRepository repository) in C:\Users\nopara\Desktop\NTumbleBit\NTumbleBit.Client\Tumbler\ClientDestinationWallet.cs:line 30
   at NTumbleBit.Tests.TumblerClientContext..ctor(TumblerClient tumblerClient, RPCClient rpcClient, IRepository clientRepository) in C:\Users\nopara\Desktop\NTumbleBit\NTumbleBit.Tests\TumblerServerTester.cs:line 27
   at NTumbleBit.Tests.TumblerServerTester..ctor(String directory) in C:\Users\nopara\Desktop\NTumbleBit\NTumbleBit.Tests\TumblerServerTester.cs:line 190
   at NTumbleBit.Tests.TumblerServerTester.Create(String caller) in C:\Users\nopara\Desktop\NTumbleBit\NTumbleBit.Tests\TumblerServerTester.cs:line 130
   at NTumbleBit.Tests.TumblerServerTests.CanCompleteCycleWithMachineState() in C:\Users\nopara\Desktop\NTumbleBit\NTumbleBit.Tests\TumblerServerTests.cs:line 63
   at DBreeze.Transactions.TransactionsJournal.Init()
   at DBreeze.DBreezeEngine.InitDb()
Result Message:	
Creation of the database folder failed!
Transaction journal couldn't clean rollback files of the finished transactions!
```

**Comment by nopara73** [comment]
I spent considerable amount of time and here is my experience:  
  
When you mess up your system (opening other softwares, stopping randomly the tests, etc) you can get a considerable amount of failed tests coming up randomly.  

Only the `TumblerServerTests` are failing.  
Everything is related to

- bitcoinds those are left open sometimes when the test fails or I terminate,  
- probably the kestrel server is failing to make some resources free too,
- various file-access problems inside TestData

I also suspect bitcoind should not be killed, too, as you do in the software. I think that would solve a lot if we could use this: http://bitcoin.stackexchange.com/questions/13696/how-to-safely-shutdown-bitcoind  
  
I noticed many of the problems are resolved by waiting a little before deletion and retry it some times, as this stackoverflow post suggest: http://stackoverflow.com/a/14933880/2061103
  
```
public static void DeleteRecursivelyWithMagicDust(string destinationDir)
{
	const int magicDust = 20;
	for (var gnomes = 1; gnomes <= magicDust; gnomes++)
	{
		try
		{
			Directory.Delete(destinationDir, true);
		}
		catch (DirectoryNotFoundException)
		{
			return;  // good!
		}
		catch (IOException)
		{ 
			// System.IO.IOException: The directory is not empty
			System.Diagnostics.Debug.WriteLine("Gnomes prevent deletion of {0}! Applying magic dust, attempt #{1}.", destinationDir, gnomes);

			// see http://stackoverflow.com/questions/329355/cannot-delete-directory-with-directory-deletepath-true for more magic
			Thread.Sleep(50);
			continue;
		}
		return;
	}
	// depending on your use case, consider throwing an exception here
}
```  
I think this should be used whenever possible, it's a better way to recursively delete, and it does not force anything, still throwing exceptions if something is wrong.

**Comment by NicolasDorier** [comment]
> bitcoind should not be programmatically killed, but properly closed: 

problem is that you don't know the port and rpc creds of the left over bitcoind.

For the magic dust solution, can you try it ? I am not sure this is the problem.

**Comment by nopara73** [comment]
Yes, as I said before it fixes about half of the problems.

**Comment by NicolasDorier** [comment]
I did not experienced any problem with tests anymore. Waxwing issues is separate.

**Comment by nopara73** [comment]
I'll keep this in my ToDo list and get back to it after we released the first version of Breeze wallet so we start working on TumbleBit integration.

**Comment by NicolasDorier** [comment]
did #37 solved everything ?

**Comment by nopara73** [comment]
So far so good. Reopen if not.
