### ISSUE TITLE
 OSX El Capitan default max open files is 256. The Client Crashes.

### ISSUE THREAD

**Issue by ezegom** [NTumbleBit/NTumbleBit#30]
Below is the log showing the exception thrown of a client crash. 

```
info: Configuration[0]
      Network: TestNet
info: Configuration[0]
      Using HOME environment variable for initializing application data
info: Configuration[0]
      Configuration file set to /Users/ezequielgomez/.ntumblebit/TestNet/client.config
info: Configuration[0]
      Testing RPC connection to http://localhost:18332/
info: Configuration[0]
      RPC connection successfull
info: Configuration[0]
      Monitor started
info: Configuration[0]
      Downloading tumbler information of http://localhost:5000/
info: Configuration[0]
      Tumbler Server Connection successfull
info: Configuration[0]
      State machines started
info: Configuration[0]
      Press enter to stop
info: Configuration[0]
      New block of height 1088045
info: Configuration[0]
      New registering cycle 1088044
info: Configuration[0]
      New state machine created
info: Configuration[0]
      Cycle 1088040 in phase ClientChannelEstablishment, ending in 1 blocks
info: Configuration[0]
      Cycle 1088042 in phase ClientChannelEstablishment, ending in 3 blocks
info: Configuration[0]
      Cycle 1088044 in phase Registration, ending in 2 blocks
info: Configuration[0]
      Registration Complete
info: Configuration[0]
      New block of height 1088046
info: Configuration[0]
      New registering cycle 1088046
info: Configuration[0]
      New state machine created
info: Configuration[0]
      Cycle 1088040 in phase TumblerChannelEstablishment, ending in 3 blocks
info: Configuration[0]
      Cycle 1088042 in phase ClientChannelEstablishment, ending in 2 blocks
info: Configuration[0]
      Cycle 1088044 in phase Registration, ending in 1 blocks
info: Configuration[0]
      Cycle 1088046 in phase Registration, ending in 3 blocks
info: Configuration[0]
      Registration Complete
info: Configuration[0]
      New block of height 1088047
info: Configuration[0]
      Cycle 1088040 in phase TumblerChannelEstablishment, ending in 2 blocks
info: Configuration[0]
      Cycle 1088042 in phase ClientChannelEstablishment, ending in 1 blocks
info: Configuration[0]
      Cycle 1088044 in phase ClientChannelEstablishment, ending in 3 blocks
info: Configuration[0]
      Client escrow broadcasted d235b36bebe85495f8e2c8afdebc1fa18e9740c0ea54ad9dc2eb0a0880d905d1
info: Configuration[0]
      Client escrow redeem c0569f27d915429ebaa323e09e8b9da5d8aae0c7478a4762919459a6b0ca190c will be broadcast later if tumbler unresponsive
info: Configuration[0]
      Cycle 1088046 in phase Registration, ending in 2 blocks
fail: Configuration[0]
      Error while running TrustedBroadcaster: An exception was thrown by a TaskScheduler.
dbug: Configuration[0]
         at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
         at System.Net.WebRequest.<>c.<GetResponseAsync>b__37_2(IAsyncResult iar)
         at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at NBitcoin.RPC.RPCClient.<SendCommandAsync>d__21.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
         at NBitcoin.RPC.RPCClient.SendCommand(RPCRequest request, Boolean throwIfRPCError)
         at NBitcoin.RPC.RPCClient.GetBlockCount()
         at NTumbleBit.Client.Tumbler.Services.RPCServices.RPCBroadcastService.Broadcast(String label, Transaction transaction)
         at NTumbleBit.Client.Tumbler.Services.RPCServices.RPCTrustedBroadcastService.TryBroadcast()
         at NTumbleBit.Client.Tumbler.Services.BroadcasterJob.<Start>b__18_0()
info: Configuration[0]
      New block of height 1088048
info: Configuration[0]
      New registering cycle 1088048
info: Configuration[0]
      New state machine created
info: Configuration[0]
      Cycle 1088040 in phase TumblerChannelEstablishment, ending in 1 blocks
info: Configuration[0]
      Cycle 1088042 in phase TumblerChannelEstablishment, ending in 3 blocks
fail: Configuration[0]
      Error while executing state machine 1088044: An exception was thrown by a TaskScheduler.
dbug: Configuration[0]
         at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
         at System.Net.WebRequest.<>c.<GetResponseAsync>b__37_2(IAsyncResult iar)
         at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at NBitcoin.RPC.RPCClient.<SendCommandAsync>d__21.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
         at NBitcoin.RPC.RPCClient.SendCommand(RPCRequest request, Boolean throwIfRPCError)
         at NBitcoin.RPC.RPCClient.GetBlockCount()
         at NTumbleBit.Client.Tumbler.Services.RPCServices.RPCBlockExplorerService.GetCurrentHeight()
         at NTumbleBit.Client.Tumbler.PaymentStateMachine.Update(ILogger logger)
         at NTumbleBit.Client.Tumbler.StateMachinesExecutor.<Start>b__30_0()

Unhandled Exception: DBreeze.Exceptions.DBreezeException: Getting table "@utNTumbleBit.Client.Tumbler.PaymentStateMachine+State" from the schema failed! ---> DBreeze.Exceptions.DBreezeException: Database is not operable, please find out the problem and restart the engine! FSR INIT FAILED: /Users/ezequielgomez/.ntumblebit/TestNet/db/Cycle_1088044/10000001 ---> System.IO.IOException: Too many open files
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Interop.CheckIo[TSafeHandle](TSafeHandle handle, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at System.IO.UnixFileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, FileStream parent)
   at System.IO.UnixFileSystem.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, FileStream parent)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at DBreeze.Storage.FSR.InitFiles()
   --- End of inner exception stack trace ---
   at DBreeze.Scheme.GetTable(String userTableName)
   --- End of inner exception stack trace ---
   at DBreeze.Transactions.TransactionsCoordinator.GetTable_READ(String tableName, Int32 transactionThreadId)
   at DBreeze.Transactions.Transaction.GetReadTableFromBuffer(String tableName, ITrieRootNode& root, Boolean AsForRead)
   at DBreeze.Transactions.Transaction.Select[TKey,TValue](String tableName, TKey key, Boolean AsReadVisibilityScope)
   at NTumbleBit.Client.Tumbler.Services.DBreezeRepository.UpdateOrInsert[T](String partitionKey, String rowKey, T data, Func`3 update)
   at NTumbleBit.Client.Tumbler.StateMachinesExecutor.Save(PaymentStateMachine stateMachine, Int32 cycle)
   at NTumbleBit.Client.Tumbler.StateMachinesExecutor.<Start>b__30_0()
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
```

**Comment by nopara73** [comment]
By googling it it seems like it is an issue related  to MAC. ("Too many open files.")  
Related: https://github.com/dotnet/corefx/issues/12503

**Comment by ezegom** [comment]
Solved: http://blog.dekstroza.io/ulimit-shenanigans-on-osx-el-capitan/ , Thank you!

**Comment by nopara73** [comment]
Not yet. It's only solved in your system :)  
Let's keep this issue open, until it's taken care in the code.

**Comment by ezegom** [comment]
Yeah, for some reason OSX El Capitan computers have a very small default number of max user processes(709) and open files (256) .

**Comment by NicolasDorier** [comment]
@ezegom can you git pull and retry again. There is a tumbler on http://testnet.ntumblebit.metaco.com/ you can run with `dotnet run -testnet -server=http://testnet.ntumblebit.metaco.com/`.  I do not think it fix it, but at least we wil have better exception trace.

**Comment by ezegom** [comment]
Alright, I'll set the number of open files and processes back to default settings and retry with the tumbler on  http://testnet.ntumblebit.metaco.com/

**Comment by NicolasDorier** [comment]
Please can you try again with my fix ? It should be ok now

**Comment by ezegom** [comment]
It seems to work correctly now. I set the settings back to default and it ran as expected, also Leen downloaded and ran recently from El Capitan with default settings without an issue! Thanks @NicolasDorier

**Comment by NicolasDorier** [comment]
Nice. I think the fact that with time the number of file open was ever gowing did not helped.
