### ISSUE TITLE
Tumbling is very slow, lot's of Client's redeem broadcasted

### ISSUE THREAD

**Issue by NicolasDorier** [NTumbleBit/NTumbleBit#34]
It seems the transaction monitor (class responsible for broadcasting transactions on time), is too slow to run when there is too many transaction.

The reason is that the `RPCTrustedBroadcaster` and `RPCBroadcaster` are calling `listtransactions` once per transaction. This can quickly escalate an take several minutes if there is 50 transactions.

It is in theory possible to call `listtransactions` once for both.

**Comment by takaya-imai** [comment]
This issue is related to the following error messages?
I got the messages in case of test cycle parameters below the message.

```
info: Main[0]
      New block of height 1112038
info: Main[0]
      New registering cycle 1112038
fail: Main[0]
      Uncaught exception StateMachineExecutor : DBreeze.Exceptions.DBreezeException: Creation of the database folder failed! ---> DBreeze.Exceptions.DBreezeException: Database is not operable, please find out the problem and restart the engine! FSR INIT FAILED: /home/takayaimai/.ntumblebit/TestNet/db/Cycle_1112038/_DBreezeSchema ---> System.IO.IOException: Too many open files
         at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
         at Interop.CheckIo[TSafeHandle](TSafeHandle handle, String path, Boolean isDirectory, Func`2 errorRewriter)
         at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
         at System.IO.UnixFileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, FileStream parent)
         at System.IO.UnixFileSystem.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, FileStream parent)
         at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
         at DBreeze.Storage.FSR.InitFiles()
         --- End of inner exception stack trace ---
         at DBreeze.Storage.FSR.InitFiles()
         at DBreeze.Storage.StorageLayer..ctor(String fileName, TrieSettings trieSettings, DBreezeConfiguration configuration)
         at DBreeze.Scheme.OpenSchema()
         at DBreeze.DBreezeEngine.InitDb()
         --- End of inner exception stack trace ---
         at DBreeze.DBreezeEngine.InitDb()
         at NTumbleBit.Client.Tumbler.Services.DBreezeRepository.GetEngine(String partitionKey)
         at NTumbleBit.Client.Tumbler.Services.DBreezeRepository.Get[T](String partitionKey, String rowKey)
         at NTumbleBit.Client.Tumbler.StateMachinesExecutor.<Start>b__30_0()
fail: Main[0]
      Uncatched exception in BroadcasterJob: System.Threading.Tasks.TaskSchedulerException: An exception was thrown by a TaskScheduler. ---> System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
         at System.Threading.Thread.StartInternal(IPrincipal principal, StackCrawlMark& stackMark)
         at System.Threading.Thread.Start(Object parameter)
         at System.Threading.Tasks.ThreadPoolTaskScheduler.QueueTask(Task task)
         at System.Threading.Tasks.Task.ScheduleAndStart(Boolean needsProtection)
         --- End of inner exception stack trace ---
         at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
         at System.Net.WebRequest.<>c.<GetResponseAsync>b__37_2(IAsyncResult iar)
         at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at NBitcoin.RPC.RPCClient.<SendCommandAsync>d__21.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
         at NBitcoin.RPC.RPCClient.SendCommand(RPCRequest request, Boolean throwIfRPCError)
         at NBitcoin.RPC.RPCClient.GetBlockCount()
         at NTumbleBit.Client.Tumbler.Services.RPCServices.RPCBlockExplorerService.GetCurrentHeight() in /home/takayaimai/NTumbleBit/NTumbleBit.TumblerServer/Services/RPCServices/RPCBlockExplorerService.cs:line 38
         at NTumbleBit.Client.Tumbler.Services.BroadcasterJob.<Start>b__18_0() in /home/takayaimai/NTumbleBit/NTumbleBit.TumblerServer/Services/BroadcasterJob.cs:line 65
```

test cycle parameters
```
                               cycle.RegistrationDuration = 2;
                               cycle.ClientChannelEstablishmentDuration = 1;
                               cycle.TumblerChannelEstablishmentDuration = 1;
                               cycle.SafetyPeriodDuration = 1;
                               cycle.PaymentPhaseDuration = 1;
                               cycle.TumblerCashoutDuration = 1;
                               cycle.ClientCashoutDuration = 1;
```

**Comment by NicolasDorier** [comment]
this is unrelated, but thanks for reporting "Too many open files" I have an idea where it comes from, will fix,

**Comment by NicolasDorier** [comment]
https://github.com/NTumbleBit/NTumbleBit/issues/35

**Comment by nopara73** [comment]
I think if this get merged the issue can be easily resolved: https://github.com/bitcoin/bitcoin/pull/9991, right?

**Comment by NicolasDorier** [comment]
I normally fixed it. I am using ListTransaction once for all transaction to broadcast.

**Comment by nopara73** [comment]
I guess you can close it and if still a problem then reopen it.

**Comment by NicolasDorier** [comment]
this is still an issue... trying to debug it.

**Comment by NicolasDorier** [comment]
fixed. Was caused by very low fee on testnet.
