### ISSUE TITLE
 Error while executing state machine 1123140: NBitcoin.RPC.RPCException: Transaction too large for fee policy

### ISSUE THREAD

**Issue by takaya-imai** [NTumbleBit/NTumbleBit#47]
I got an error when I tried codes for the latest commit https://github.com/NTumbleBit/NTumbleBit/commit/b9dfa56103e78d4291e141275f502118c8555ccc on testnet.

```
info: Main[0]
      Registration Complete
info: Main[0]
      New block of height 1123143
info: Main[0]
      Cycle 1123138 in phase ClientChannelEstablishment, ending in 1 blocks
info: Main[0]
      Cycle 1123140 in phase ClientChannelEstablishment, ending in 3 blocks
fail: Main[0]
      Error while executing state machine 1123140: NBitcoin.RPC.RPCException: Transaction too large for fee policy
         at NBitcoin.RPC.RPCResponse.ThrowIfError()
         at NBitcoin.RPC.RPCClient.<SendCommandAsync>d__21.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at NBitcoin.RPC.RPCClient.<FundRawTransactionAsync>d__84.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at NBitcoin.RPC.RPCClient.FundRawTransaction(Transaction transaction, FundRawTransactionOptions options)
         at NTumbleBit.Client.Tumbler.Services.RPCServices.RPCWalletService.FundTransaction(TxOut txOut, FeeRate feeRate) in /home/xxxx/NTumbleBit/NTumbleBit.TumblerServer/Services/RPCServices/RPCWalletService.cs:line 70
         at NTumbleBit.Client.Tumbler.PaymentStateMachine.Update(ILogger logger) in /home/xxxx/NTumbleBit/NTumbleBit.Client/Tumbler/PaymentStateMachine.cs:line 183
         at NTumbleBit.Client.Tumbler.StateMachinesExecutor.<Start>b__30_0() in /home/xxxx/NTumbleBit/NTumbleBit.Client/Tumbler/StateMachinesExecutor.cs:line 106
```

**Comment by takaya-imai** [comment]
It is resolved by https://github.com/NTumbleBit/NTumbleBit/commit/513de5fddd5ea6315dc12c0f3cdadf6500bb9596 .
