### ISSUE TITLE
Error while executing state machine 1125088: NTumbleBit.PuzzleSolver.PuzzleException: Impossible to find solution to the puzzle

### ISSUE THREAD

**Issue by takaya-imai** [NTumbleBit/NTumbleBit#48]
I got an error for Client Cashout as the end of this issue.

At first, I did not get why a solution Bob has can not solve the puzzle Bob already had
since the solution is checked through Puzzle Solver Protocol.

Investigating tx, it looks that Puzzle Solver Protocol is skipped or failed.
So it might be better that client write failure into log if the protocol failed due to no response from tumbler etc.

**Error Message**
```
fail: Main[0]
      Error while executing state machine 1125088: NTumbleBit.PuzzleSolver.PuzzleException: Impossible to find solution to the puzzle
         at NTumbleBit.PuzzleSolver.SolverClientSession.CheckSolutions(Transaction[] transactions) in /home/takayaimai/NTumbleBit/NTumbleBit/PuzzleSolver/SolverClientSession.cs:line 395
         at NTumbleBit.Client.Tumbler.PaymentStateMachine.Update(ILogger logger) in /home/takayaimai/NTumbleBit/NTumbleBit.Client/Tumbler/PaymentStateMachine.cs:line 298
         at NTumbleBit.Client.Tumbler.StateMachinesExecutor.<Start>b__30_0() in /home/takayaimai/NTumbleBit/NTumbleBit.Client/Tumbler/StateMachinesExecutor.cs:line 106
```

```
fail: Main[0]
      Error while executing state machine 1125138: NTumbleBit.PuzzleSolver.PuzzleException: Impossible to find solution to the puzzle
         at NTumbleBit.PuzzleSolver.SolverClientSession.CheckSolutions(Transaction[] transactions) in /home/xxxx/NTumbleBit/NTumbleBit/PuzzleSolver/SolverClientSession.cs:line 395
         at NTumbleBit.Client.Tumbler.PaymentStateMachine.Update(ILogger logger) in /home/xxxx/NTumbleBit/NTumbleBit.Client/Tumbler/PaymentStateMachine.cs:line 298
         at NTumbleBit.Client.Tumbler.StateMachinesExecutor.<Start>b__30_0() in /home/xxxx/NTumbleBit/NTumbleBit.Client/Tumbler/StateMachinesExecutor.cs:line 106
```

**Phase Transitions**
```
$ grep 1125088 ~/tumblebit_client.txt
      New registering cycle 1125088
      Cycle 1125088 in phase Registration, ending in 2 blocks
      Cycle 1125088 in phase Registration, ending in 1 blocks
      Cycle 1125088 in phase ClientChannelEstablishment, ending in 3 blocks
      Cycle 1125088 in phase ClientChannelEstablishment, ending in 2 blocks
      Cycle 1125088 in phase ClientChannelEstablishment, ending in 1 blocks
      Cycle 1125088 in phase TumblerChannelEstablishment, ending in 3 blocks
      Cycle 1125088 in phase TumblerChannelEstablishment, ending in 2 blocks
      Cycle 1125088 in phase TumblerChannelEstablishment, ending in 1 blocks
      Cycle 1125088 in phase PaymentPhase, ending in 3 blocks
      Cycle 1125088 in phase PaymentPhase, ending in 2 blocks
      Cycle 1125088 in phase PaymentPhase, ending in 1 blocks
      Cycle 1125088 in phase TumblerCashoutPhase, ending in 1 blocks
      Cycle 1125088 in phase ClientCashoutPhase, ending in 3 blocks
      Error while executing state machine 1125088: NTumbleBit.PuzzleSolver.PuzzleException: Impossible to find solution to the puzzle
      Cycle 1125088 in phase ClientCashoutPhase, ending in 2 blocks
      Error while executing state machine 1125088: NTumbleBit.PuzzleSolver.PuzzleException: Impossible to find solution to the puzzle
      Cycle 1125088 in phase ClientCashoutPhase, ending in 1 blocks
      Error while executing state machine 1125088: NTumbleBit.PuzzleSolver.PuzzleException: Impossible to find solution to the puzzle
```

```
$ grep 1125138 ~/tumblebit_client.txt
      New block of height 1125138
      New registering cycle 1125138
      Cycle 1125138 in phase Registration, ending in 3 blocks
      Cycle 1125138 in phase Registration, ending in 2 blocks
      Cycle 1125138 in phase Registration, ending in 1 blocks
      Cycle 1125138 in phase ClientChannelEstablishment, ending in 3 blocks
      Cycle 1125138 in phase ClientChannelEstablishment, ending in 2 blocks
      Cycle 1125138 in phase ClientChannelEstablishment, ending in 1 blocks
      Cycle 1125138 in phase TumblerChannelEstablishment, ending in 3 blocks
      Cycle 1125138 in phase TumblerChannelEstablishment, ending in 2 blocks
      Cycle 1125138 in phase TumblerChannelEstablishment, ending in 1 blocks
      Cycle 1125138 in phase PaymentPhase, ending in 3 blocks
      Cycle 1125138 in phase PaymentPhase, ending in 2 blocks
      Cycle 1125138 in phase PaymentPhase, ending in 1 blocks
      Cycle 1125138 in phase TumblerCashoutPhase, ending in 1 blocks
      Cycle 1125138 in phase ClientCashoutPhase, ending in 3 blocks
      Error while executing state machine 1125138: NTumbleBit.PuzzleSolver.PuzzleException: Impossible to find solution to the puzzle
      Cycle 1125138 in phase ClientCashoutPhase, ending in 2 blocks
      Error while executing state machine 1125138: NTumbleBit.PuzzleSolver.PuzzleException: Impossible to find solution to the puzzle
      Cycle 1125138 in phase ClientCashoutPhase, ending in 1 blocks
      Error while executing state machine 1125138: NTumbleBit.PuzzleSolver.PuzzleException: Impossible to find solution to the puzzle
```

**Transactions for Client Channel Establishment and Puzzle Solver Protocol**
Cycle 1125088: 
tx for Client Channel Establishment:  https://testnet.smartbit.com.au/address/2N3NnAvP6AyuL4YRdaqeSrRmBPhZ61P2b5t
no tx for Puzzle Solver Protocol(Payment Phase): 
<img width="1237" alt="2017-05-22 1 05 37" src="https://cloud.githubusercontent.com/assets/2457450/26285445/e4495110-3e8a-11e7-912c-f60675c90485.png">

Cycle 1125138: 
tx for Client Channel Establishment:  https://testnet.smartbit.com.au/tx/b99a851ce9cb21d344c70714a5a742505a2308aebefbbbbcc9939287a97fef17
no tx for Puzzle Solver Protocol(Payment Phase): 
<img width="1219" alt="2017-05-22 1 07 46" src="https://cloud.githubusercontent.com/assets/2457450/26285456/1b57a756-3e8b-11e7-8209-d3470989d597.png">

**Comment by zeptin** [comment]
I am also encountering this error on my testnet tumbler clients. Did you find a solution?

**Comment by NicolasDorier** [comment]
woops, I missed the issue. Yes, it can happen if there is a delay between block propagation between server and client. This is actually harmless.

**Comment by NicolasDorier** [comment]
hu actually no

**Comment by NicolasDorier** [comment]
@takaya-imai @zeptin just updated my node, can you try again ?

**Comment by NicolasDorier** [comment]
Fixed
