### ISSUE TITLE
Client:         StateMachine Error: NTumbleBit.Tor.SocksException: TTL expired

### ISSUE THREAD

**Issue by takaya-imai** [NTumbleBit/NTumbleBit#84]
I got the following error from client.
My tor setting for client side is wrong?

```
Client:         StateMachine Error: NTumbleBit.Tor.SocksException: TTL expired
         at NTumbleBit.Tor.SocksMessageHandler.<CreateSocket>d__3.MoveNext() in /home/xxx/NTumbleBit/NTumbleBit/Tor/SocksMessageHandler.cs:line 137
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at TCPServer.Client.TCPHttpMessageHandler.<>c__DisplayClass12_0.<<EnsureConnectedAsync>b__0>d.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at TCPServer.Client.TCPHttpMessageHandler.<EnsureConnectedAsync>d__12.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at TCPServer.Client.TCPHttpMessageHandler.<SendAsyncCore>d__8.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at TCPServer.Client.TCPHttpMessageHandler.<SendAsync>d__7.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
         at System.Net.Http.HttpClient.<FinishSendAsync>d__58.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
         at NTumbleBit.ClassicTumbler.Client.TumblerClient.<SendAsync>d__25`1.MoveNext() in /home/xxx/NTumbleBit/NTumbleBit/ClassicTumbler/Client/TumblerClient.cs:line 132
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
         at NTumbleBit.ClassicTumbler.Client.TumblerClient.SignVoucher(SignVoucherRequest signVoucherRequest) in /home/xxx/NTumbleBit/NTumbleBit/ClassicTumbler/Client/TumblerClient.cs:line 80
         at NTumbleBit.ClassicTumbler.Client.PaymentStateMachine.Update() in /home/xxx/NTumbleBit/NTumbleBit/ClassicTumbler/Client/PaymentStateMachine.cs:line 258
         at NTumbleBit.ClassicTumbler.Client.StateMachinesExecutor.<>c__DisplayClass7_0.<StartCore>b__0() in /home/xxx/NTumbleBit/NTumbleBit/ClassicTumbler/Client/StateMachinesExecutor.cs:line 66
```

**Comment by NicolasDorier** [comment]
somebody else also told me about same error, does it disappear after a while ?

**Comment by Yzord** [comment]
I had this error a lot when i was connected to the server of Nicolas, but never got this error anymore when i was connected to my Linux server.

**Comment by NicolasDorier** [comment]
Fixed this one. TOR keep retrying until no TTL
