### ISSUE TITLE
fail: Client:         StateMachine Error: System.Threading.Tasks.TaskCanceledException: A task was canceled.

### ISSUE THREAD

**Issue by Yzord** [NTumbleBit/NTumbleBit#91]
7 of 8 clients spitted out this error. Number 8 was still running. Restarted the clients made them working again

> fail: Client:         StateMachine Error: System.Threading.Tasks.TaskCanceledException: A task was canceled.
         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
         at NTumbleBit.Tor.SocksMessageHandler.<CreateSocket>d__3.MoveNext() in /home/stratis/NTumbleBit/NTumbleBit/Tor/SocksMessageHandler.cs:line 137
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at TCPServer.Client.TCPHttpMessageHandler.<>c__DisplayClass12_0.<<EnsureConnectedAsync>b__0>d.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at TCPServer.Client.TCPHttpMessageHandler.<EnsureConnectedAsync>d__12.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at TCPServer.Client.TCPHttpMessageHandler.<SendAsyncCore>d__8.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at TCPServer.Client.TCPHttpMessageHandler.<SendAsync>d__7.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
         at System.Net.Http.HttpClient.<FinishSendAsync>d__58.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
stratis@TBclient3:~$ bitcoin-cli getinfo
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
         at NTumbleBit.ClassicTumbler.Client.TumblerClient.<SendAsync>d__25`1.MoveNext() in /home/stratis/NTumbleBit/NTumbleBit/ClassicTumbler/Client/TumblerClient.cs:line 132
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
         at NTumbleBit.ClassicTumbler.Client.TumblerClient.RequestTumblerEscrowKey() in /home/stratis/NTumbleBit/NTumbleBit/ClassicTumbler/Client/TumblerClient.cs:line 102
         at NTumbleBit.ClassicTumbler.Client.PaymentStateMachine.Update() in /home/stratis/NTumbleBit/NTumbleBit/ClassicTumbler/Client/PaymentStateMachine.cs:line 210
         at NTumbleBit.ClassicTumbler.Client.StateMachinesExecutor.<>c__DisplayClass7_0.<StartCore>b__0() in /home/stratis/NTumbleBit/NTumbleBit/ClassicTumbler/Client/StateMachinesExecutor.cs:line 66

**Comment by NicolasDorier** [comment]
closing, I fixed this one.
